const actionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAIL: 'GET_ALL_CATEGORIES_FAIL',

    GET_POSTS: "GET_POSTS",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: "GET_POSTS_ADMIN",
    FILTER_POSTS_ADMIN: 'FILTER_POSTS_ADMIN',
    GET_NEW_POST: "GET_NEW_POST",
    EDIT_DATA: 'EDIT_DATA',
    CLEAR_EDIT_DATA: 'CLEAR_EDIT_DATA',

    GET_PRICES_SUCCESS: "GET_PRICES_SUCCESS",
    GET_PRICES_FAIL: "GET_PRICES_FAIL",

    GET_AREAS_SUCCESS: "GET_AREAS_SUCCESS",
    GET_AREAS_FAIL: "GET_AREAS_FAIL",

    GET_PROVINCE_SUCCESS: "GET_PROVINCE_SUCCESS",
    GET_PROVINCE_FAIL: "GET_PROVINCE_FAIL",

    GET_CURRENT:'GET_CURRENT'
}

export default actionTypes